[package]
name = "advent17"
version = "0.1.0"
authors = ["Krzysztof Drewniak <krzysdrewniak@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static="1"
rustc-hash="1.1"
nalgebra="0.23"